services:
  fastapi:
    image: jaylaksh94/fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
 
  streamlit:
    image: jaylaksh94/streamlit:latest
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      API_URL: "http://fastapi:8000"
