apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: model
  name: model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model
  strategy: {}
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: house-pricemodel
          image: jaylaksh94/house-pricemodel:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
